week3
deminovamv/week3 pull request #1
Opened 2021-05-23 14:11 UTC by deminovamv

2021-05-27 15:09 UTC, statz requested changes

2021-05-27 15:09 UTC, statz commented on for_challenges.py
> +for group in groups:
Можно было использовать enumerate

2021-05-27 15:09 UTC, statz commented on for_dict_challenges.py
> +    name_dict = {}
Можно было использовать defaultdict из модуля collections. А вообще там же есть специально предназначенный для таких задач Counter, но это на будущее)

2021-05-27 15:09 UTC, statz commented on for_dict_challenges.py
> +def count_name_dict(name_dict):
Можно оптимизировать функцию, чтобы вычилсять за один проход самое популярное имя. Например, идти по словарю, на каждом шаге сравнивать сколько раз встречалось текущее имя с масимум по предыдущим именам. Если текущее встречалось чаще, то обновляем максимум и запоминаем это имя.

2021-05-27 15:09 UTC, statz commented on for_dict_challenges.py
> +    for k,v in name_class.items():
Я на встрече говорил, что не стоит проходиться по элементам словаря и сравнивать их с ключами, когда можно просто достать сразу по ключу

2021-05-27 15:09 UTC, statz commented on for_dict_challenges.py
> +    class_name, boys, girls = count_boys_and_girls(name_class)
а тут точно правильное задание сделано? требуется найти класс с самым большим числом мальчиков и самым большим числом девочек

2021-05-27 15:09 UTC, statz commented on for_dict_challenges.py
> +    if boys > girls:
а тут мы просто выводим, если мальчиков в классе больше, чем девочек

2021-05-30 11:19 UTC, deminovamv commented on for_dict_challenges.py
> +    class_name, boys, girls = count_boys_and_girls(name_class)
не так условие поняла, переделала немного

2021-06-02 09:28 UTC, statz approved these changes

2021-12-01 15:04 UTC, merged